language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXFLAGS="-Wall -Wextra -Wno-maybe-uninitialized -Werror -O3"

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXSTD="-std=c++17"
        - CXXFLAGS="-Wall -Wextra -Wno-maybe-uninitialized -Werror -O3"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5', 'g++-4.9']
      env:
        - COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9']
      env:
        - COMPILER=clang++-3.9

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0 CXXSTD="-std=c++1z"

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env:
        - COMPILER=clang++

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user urllib3[secure] cpp-coveralls
        # Work around https://github.com/eddyxu/cpp-coveralls/issues/108 by manually
        # installing the pyOpenSSL module and injecting it into urllib3 as per
        # https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
        - sed -i -e '/^import sys$/a import urllib3.contrib.pyopenssl\nurllib3.contrib.pyopenssl.inject_into_urllib3()' $(which coveralls)
      after_success:
        - coveralls --gcov gcov-6 --gcov-options '\-lp' --exclude src --exclude include/tao/json/external

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CPPFLAGS=-fsanitize=undefined
        - COMPILER=g++-7

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CPPFLAGS="-fsanitize=address -fuse-ld=gold"
        - COMPILER=g++-7

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CPPFLAGS=-fsanitize=undefined
        - COMPILER=clang++-4.0

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CPPFLAGS=-fsanitize=address
        - COMPILER=clang++-4.0

script:
  make CXX=$COMPILER -j3
