language: generic
os: linux
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - compiler: gcc
      env:
        - CXX=g++-4.8

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX=g++-4.9

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX=g++-5

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX=g++-6

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX=g++-6
        - CXXSTD=-std=c++14

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXSTD=-std=c++17

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.5', 'g++-4.9']
      env:
        - CXX=clang++-3.5

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.6']
      env:
        - CXX=clang++-3.6

    - dist: precise
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - CXX=clang++-3.7

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.8']
      env:
        - CXX=clang++-3.8

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.9']
      env:
        - CXX=clang++-3.9

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CXX=clang++-4.0

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CXX=clang++-4.0
        - CXXSTD=-std=c++14

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env:
        - CXX=clang++-5.0

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']
      env:
        - CXX=clang++-5.0
        - CXXSTD=-std=c++17

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - CXX=clang++

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      script:
        - make -kj3 check
        - coveralls --gcov gcov-7 --gcov-options '\-lp' --exclude src --exclude include/tao/json/external

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CPPFLAGS=-fsanitize=undefined

    - compiler: gcc
      sudo: required
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CPPFLAGS="-fsanitize=address -fuse-ld=gold"

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env:
        - CXX=clang++-5.0
        - CPPFLAGS=-fsanitize=undefined

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env:
        - CXX=clang++-5.0
        - CPPFLAGS=-fsanitize=address

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'clang-tidy-5.0']
      env:
        - CXX=clang++-5.0
        - CLANG_TIDY=clang-tidy-5.0
      script:
        - make -kj3 clang-tidy

script:
  - $CXX --version
  - make -kj3
